// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/khevse/codegen/tests/mainpkg.IObject1 -o i_object1_mock.go -n IObject1Mock -p mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// IObject1Mock implements mm_mainpkg.IObject1
type IObject1Mock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcString          func() (s1 string)
	funcStringOrigin    string
	inspectFuncString   func()
	afterStringCounter  uint64
	beforeStringCounter uint64
	StringMock          mIObject1MockString
}

// NewIObject1Mock returns a mock for mm_mainpkg.IObject1
func NewIObject1Mock(t minimock.Tester) *IObject1Mock {
	m := &IObject1Mock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.StringMock = mIObject1MockString{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mIObject1MockString struct {
	optional           bool
	mock               *IObject1Mock
	defaultExpectation *IObject1MockStringExpectation
	expectations       []*IObject1MockStringExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// IObject1MockStringExpectation specifies expectation struct of the IObject1.String
type IObject1MockStringExpectation struct {
	mock *IObject1Mock

	results      *IObject1MockStringResults
	returnOrigin string
	Counter      uint64
}

// IObject1MockStringResults contains results of the IObject1.String
type IObject1MockStringResults struct {
	s1 string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmString *mIObject1MockString) Optional() *mIObject1MockString {
	mmString.optional = true
	return mmString
}

// Expect sets up expected params for IObject1.String
func (mmString *mIObject1MockString) Expect() *mIObject1MockString {
	if mmString.mock.funcString != nil {
		mmString.mock.t.Fatalf("IObject1Mock.String mock is already set by Set")
	}

	if mmString.defaultExpectation == nil {
		mmString.defaultExpectation = &IObject1MockStringExpectation{}
	}

	return mmString
}

// Inspect accepts an inspector function that has same arguments as the IObject1.String
func (mmString *mIObject1MockString) Inspect(f func()) *mIObject1MockString {
	if mmString.mock.inspectFuncString != nil {
		mmString.mock.t.Fatalf("Inspect function is already set for IObject1Mock.String")
	}

	mmString.mock.inspectFuncString = f

	return mmString
}

// Return sets up results that will be returned by IObject1.String
func (mmString *mIObject1MockString) Return(s1 string) *IObject1Mock {
	if mmString.mock.funcString != nil {
		mmString.mock.t.Fatalf("IObject1Mock.String mock is already set by Set")
	}

	if mmString.defaultExpectation == nil {
		mmString.defaultExpectation = &IObject1MockStringExpectation{mock: mmString.mock}
	}
	mmString.defaultExpectation.results = &IObject1MockStringResults{s1}
	mmString.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmString.mock
}

// Set uses given function f to mock the IObject1.String method
func (mmString *mIObject1MockString) Set(f func() (s1 string)) *IObject1Mock {
	if mmString.defaultExpectation != nil {
		mmString.mock.t.Fatalf("Default expectation is already set for the IObject1.String method")
	}

	if len(mmString.expectations) > 0 {
		mmString.mock.t.Fatalf("Some expectations are already set for the IObject1.String method")
	}

	mmString.mock.funcString = f
	mmString.mock.funcStringOrigin = minimock.CallerInfo(1)
	return mmString.mock
}

// Times sets number of times IObject1.String should be invoked
func (mmString *mIObject1MockString) Times(n uint64) *mIObject1MockString {
	if n == 0 {
		mmString.mock.t.Fatalf("Times of IObject1Mock.String mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmString.expectedInvocations, n)
	mmString.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmString
}

func (mmString *mIObject1MockString) invocationsDone() bool {
	if len(mmString.expectations) == 0 && mmString.defaultExpectation == nil && mmString.mock.funcString == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmString.mock.afterStringCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmString.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// String implements mm_mainpkg.IObject1
func (mmString *IObject1Mock) String() (s1 string) {
	mm_atomic.AddUint64(&mmString.beforeStringCounter, 1)
	defer mm_atomic.AddUint64(&mmString.afterStringCounter, 1)

	mmString.t.Helper()

	if mmString.inspectFuncString != nil {
		mmString.inspectFuncString()
	}

	if mmString.StringMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmString.StringMock.defaultExpectation.Counter, 1)

		mm_results := mmString.StringMock.defaultExpectation.results
		if mm_results == nil {
			mmString.t.Fatal("No results are set for the IObject1Mock.String")
		}
		return (*mm_results).s1
	}
	if mmString.funcString != nil {
		return mmString.funcString()
	}
	mmString.t.Fatalf("Unexpected call to IObject1Mock.String.")
	return
}

// StringAfterCounter returns a count of finished IObject1Mock.String invocations
func (mmString *IObject1Mock) StringAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmString.afterStringCounter)
}

// StringBeforeCounter returns a count of IObject1Mock.String invocations
func (mmString *IObject1Mock) StringBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmString.beforeStringCounter)
}

// MinimockStringDone returns true if the count of the String invocations corresponds
// the number of defined expectations
func (m *IObject1Mock) MinimockStringDone() bool {
	if m.StringMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.StringMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.StringMock.invocationsDone()
}

// MinimockStringInspect logs each unmet expectation
func (m *IObject1Mock) MinimockStringInspect() {
	for _, e := range m.StringMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to IObject1Mock.String")
		}
	}

	afterStringCounter := mm_atomic.LoadUint64(&m.afterStringCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.StringMock.defaultExpectation != nil && afterStringCounter < 1 {
		m.t.Errorf("Expected call to IObject1Mock.String at\n%s", m.StringMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcString != nil && afterStringCounter < 1 {
		m.t.Errorf("Expected call to IObject1Mock.String at\n%s", m.funcStringOrigin)
	}

	if !m.StringMock.invocationsDone() && afterStringCounter > 0 {
		m.t.Errorf("Expected %d calls to IObject1Mock.String at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.StringMock.expectedInvocations), m.StringMock.expectedInvocationsOrigin, afterStringCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IObject1Mock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockStringInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IObject1Mock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IObject1Mock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockStringDone()
}
